/* Used in AuthReducer */
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "LOGOUT_FAILURE";

export const VERIFY_REQUEST = "VERIFY_REQUEST";
export const VERIFY_SUCCESS = "VERIFY_SUCCESS";

export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_FAILURE = "SIGNUP_FAILURE";

/* Used in UserReducer */
export const INIT_USER_REQUEST = "INIT_USER_REQUEST";
export const INIT_USER_SUCCESS = "INIT_USER_SUCCESS";
export const INIT_USER_FAILURE = "INIT_USER_FAILURE";

export const GET_GOALS_REQUEST = "GET_GOALS_REQUEST";
export const GET_GOALS_SUCCESS = "GET_GOALS_SUCCESS";
export const GET_GOALS_FAILURE = "GET_GOALS_FAILURE";
