name: Lint

on:
  pull_request:
    branches: [master]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: Install prettier
        run: npm install --global prettier

      - name: Run linters
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir: ./ReactNative/componenets, ./ReactNative/src/navigator, ./ReactNative/src/redux, ./ReactNative/src/screens, ./ReactNative/src/styles, ./ReactNative/src/utils, ./ReactNative/src/App.js
          # Enable linters
          prettier: true

defaults:
  run:
    working-directory: ./ReactNative
