name: Lint

on:
  pull_request:
    branches: [master]
jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: npm install

      - name: Install prettier
        run: npm install --global prettier

      - name: Run lint components 
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir: ./ReactNative/components
          # Enable linters
          prettier: true
          
      - name: Run lint navigator 
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir: ./ReactNative/src/navigator
          # Enable linters
          prettier: true
          
      - name: Run lint redux 
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir: ./ReactNative/src/redux
          # Enable linters
          prettier: true
         
      - name: Run lint screens 
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir:  ./ReactNative/src/screens
          # Enable linters
          prettier: true
          
      - name: Run lint styles 
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir: ./ReactNative/src/styles
          # Enable linters
          prettier: true
      
      - name: Run lint utils 
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir: ./ReactNative/src/utils
          # Enable linters
          prettier: true
      
      - name: Run lint App.js 
        uses: samuelmeuli/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          prettier_dir: ./ReactNative/src/App.js
          # Enable linters
          prettier: true

defaults:
  run:
    working-directory: ./ReactNative
